'use client';

import { useState, useEffect } from 'react';
import { trainingService } from '@/lib/services/trainingService';
import { testService } from '@/lib/services/testService';
import { TrainingPath, UserProgress, TestResult } from '@/types';
import { useLanguage } from '@/lib/i18n/LanguageContext';
import { useAuth } from '@/contexts/AuthContext';
import { 
  CheckCircle2, 
  Circle, 
  PlayCircle, 
  FileText, 
  HelpCircle, 
  FileEdit,
  ChevronRight,
  ChevronDown,
  ArrowLeft,
  Clock,
  Award
} from 'lucide-react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import styles from './path-detail.module.css';
import toast from 'react-hot-toast';

export function PathDetailContent({ id }: { id: string }) {
  const { t, language } = useLanguage();
  const { user } = useAuth();
  const [path, setPath] = useState<TrainingPath | null>(null);
  const [progress, setProgress] = useState<UserProgress[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedStages, setExpandedStages] = useState<string[]>([]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const pathData = await trainingService.getPathById(id);
      if (pathData) {
        setPath(pathData);
        setExpandedStages([pathData.stages[0]?.id]); // Expand first stage by default
        
        if (user) {
          const progressData = await trainingService.getAllUserProgress();
          setProgress(progressData.filter(p => p.userId === user.id && p.pathId === id));
        }
      }
    } catch (e) {
      toast.error('Failed to load path data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [id, user]);

  const toggleStage = (stageId: string) => {
    setExpandedStages(prev => 
      prev.includes(stageId) ? prev.filter(s => s !== stageId) : [...prev, stageId]
    );
  };

  const isTaskCompleted = (taskId: string) => {
    return progress.find(p => p.taskId === taskId)?.completed;
  };

  const handleCompleteTask = async (stageId: string, taskId: string) => {
    if (!user || !path) return;
    
    try {
      await trainingService.updateTaskProgress({
        userId: user.id,
        pathId: path.id,
        stageId,
        taskId,
        completed: true,
        id: '' // will be generated by service
      });
      toast.success('Task completed!');
      fetchData();
    } catch (e) {
      toast.error('Update failed');
    }
  };

  if (loading) return <div className={styles.loading}>Loading training details...</div>;
  if (!path) return <div className={styles.error}>Path not found</div>;

  const totalTasks = path.stages.reduce((acc, s) => acc + s.tasks.length, 0);
  const completedTasks = progress.filter(p => p.completed).length;
  const progressPercent = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  return (
    <div className="animate-fade-in">
      <div className={styles.header}>
        <Link href="/dashboard/hr/training" className={styles.backBtn}>
          <ArrowLeft size={20} />
          {t('backToCandidates') || 'Back'}
        </Link>
        
        <div className={styles.headerContent}>
           <div className={styles.pathInfo}>
              <h1 className={styles.title}>{path.title}</h1>
              <p className={styles.desc}>{path.description}</p>
           </div>
           <div className={styles.progressCircleContainer}>
              <div className={styles.progressCircle}>
                 <svg viewBox="0 0 36 36" className={styles.circularChart}>
                    <path className={styles.circleBg} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    <path className={styles.circle} strokeDasharray={`${progressPercent}, 100`} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    <text x="18" y="20.35" className={styles.percentage}>{progressPercent}%</text>
                 </svg>
              </div>
              <div className={styles.progressText}>
                <span>{completedTasks} / {totalTasks} {t('training.tasks')}</span>
              </div>
           </div>
        </div>
      </div>

      <div className={styles.content}>
        <div className={styles.stagesList}>
          {path.stages.sort((a,b) => a.order - b.order).map((stage, idx) => {
            const isExpanded = expandedStages.includes(stage.id);
            const stageCompletedTasks = stage.tasks.filter(t => isTaskCompleted(t.id)).length;
            const isStageDone = stageCompletedTasks === stage.tasks.length && stage.tasks.length > 0;

            return (
              <div key={stage.id} className={`${styles.stageItem} ${isExpanded ? styles.stageExpanded : ''}`}>
                <div className={styles.stageHeader} onClick={() => toggleStage(stage.id)}>
                   <div className={styles.stageStatus}>
                      {isStageDone ? <CheckCircle2 className={styles.doneIcon} /> : <div className={styles.stepNum}>{idx + 1}</div>}
                   </div>
                   <div className={styles.stageInfo}>
                      <h3>{stage.title}</h3>
                      <p>{stage.description}</p>
                   </div>
                   <div className={styles.stageMeta}>
                      <span className={styles.stageTime}><Clock size={14} /> {stage.estimatedHours}h</span>
                      {isExpanded ? <ChevronDown size={20} /> : <ChevronRight size={20} />}
                   </div>
                </div>

                <AnimatePresence>
                  {isExpanded && (
                    <motion.div 
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className={styles.tasksList}
                    >
                      {stage.tasks.map(task => {
                        const done = isTaskCompleted(task.id);
                        return (
                          <div key={task.id} className={`${styles.taskItem} ${done ? styles.taskDone : ''}`}>
                             <div className={styles.taskTypeIcon}>
                                {task.type === 'video' && <PlayCircle size={20} />}
                                {task.type === 'article' && <FileText size={20} />}
                                {task.type === 'quiz' && <Award size={20} />}
                                {task.type === 'assignment' && <FileEdit size={20} />}
                             </div>
                             <div className={styles.taskInfo}>
                                <h4>{task.title}</h4>
                                <span className={styles.taskType}>{t(`training.type.${task.type}`)} • {task.estimatedMinutes}m</span>
                             </div>
                             <div className={styles.taskAction}>
                                {done ? (
                                  <span className={styles.completedBadge}>
                                    <CheckCircle2 size={16} /> {t('verified')}
                                  </span>
                                ) : (
                                  <button onClick={() => handleCompleteTask(stage.id, task.id)} className={styles.completeBtn}>
                                    {t('tests.startTest')}
                                  </button>
                                )}
                             </div>
                          </div>
                        );
                      })}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

        <div className={styles.sidebar}>
           <div className={styles.sidebarCard}>
              <h3>Next Goal</h3>
              <p>Continue your journey and master React patterns!</p>
              <div className={styles.nextTaskCard}>
                 <Zap className={styles.zapIcon} />
                 <div>
                    <span style={{ fontSize: '0.7rem', opacity: 0.7 }}>NEXT TASK</span>
                    <div style={{ fontWeight: 700 }}>{path.stages[0]?.tasks.find(t => !isTaskCompleted(t.id))?.title || 'All done!'}</div>
                 </div>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}

function Zap(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
    </svg>
  );
}
